// node --test scripts/__tests__/bump-version.test.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { bumpAll, bumpCargoLock, bumpCargoToml, bumpJson, TARGETS } from '../bump-version.mjs';

const SCRIPT = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'bump-version.mjs');

const CARGO_TOML = `# comment with version = "9.9.9" that must not change
[workspace]
members = ["crates/*"]

[package]
name = "cortexmd-cli"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "cortexmd"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
`;

const CARGO_LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anyhow"
version = "1.0.102"

[[package]]
name = "cortexmd-cli"
version = "0.2.0"
dependencies = [
 "anyhow",
]

[[package]]
name = "zzz"
version = "0.2.0"
`;

function fixtureRepo() {
  const root = mkdtempSync(join(tmpdir(), 'bump-version-'));
  mkdirSync(join(root, 'crates', 'cli'), { recursive: true });
  mkdirSync(join(root, 'packages', 'server'), { recursive: true });
  mkdirSync(join(root, 'plugin', 'cortexmd', '.claude-plugin'), { recursive: true });
  writeFileSync(join(root, 'crates', 'cli', 'Cargo.toml'), CARGO_TOML);
  writeFileSync(join(root, 'Cargo.lock'), CARGO_LOCK);
  writeFileSync(
    join(root, 'packages', 'server', 'package.json'),
    '{\n  "name": "cortexmd-server",\n  "version": "1.0.0",\n  "scripts": { "version": "echo not-a-version" }\n}\n'
  );
  writeFileSync(join(root, 'package.json'), '{\n  "name": "cortexmd",\n  "private": true,\n  "workspaces": [\n    "packages/*"\n  ]\n}\n');
  writeFileSync(
    join(root, 'plugin', 'cortexmd', '.claude-plugin', 'plugin.json'),
    '{\n  "name": "cortexmd",\n  "displayName": "cortexmd",\n  "version": "0.2.0",\n  "keywords": ["mcp", "memory"]\n}\n'
  );
  return root;
}

test('bumpCargoToml only touches [package].version', () => {
  const out = bumpCargoToml(CARGO_TOML, '1.19.0');
  assert.match(out, /\[package\]\nname = "cortexmd-cli"\nversion = "1.19.0"\n/);
  assert.ok(out.includes('# comment with version = "9.9.9"'), 'comment untouched');
  assert.ok(out.includes('serde = { version = "1.0.228"'), 'dependency version untouched');
  assert.equal(out.length, CARGO_TOML.length + '1.19.0'.length - '0.2.0'.length);
});

test('bumpCargoLock edits only the cortexmd-cli entry', () => {
  const out = bumpCargoLock(CARGO_LOCK, '1.19.0');
  assert.ok(out.includes('name = "cortexmd-cli"\nversion = "1.19.0"'));
  assert.ok(out.includes('name = "zzz"\nversion = "0.2.0"'), 'other 0.2.0 package untouched');
  assert.ok(out.includes('name = "anyhow"\nversion = "1.0.102"'));
  assert.throws(() => bumpCargoLock('[[package]]\nname = "other"\nversion = "1.0.0"\n', '1.0.1'), /no \[\[package\]\] entry/);
});

test('bumpCargoLock handles CRLF lockfiles', () => {
  const crlf = CARGO_LOCK.replace(/\n/g, '\r\n');
  const out = bumpCargoLock(crlf, '2.0.0');
  assert.ok(out.includes('name = "cortexmd-cli"\r\nversion = "2.0.0"'));
});

test('bumpJson preserves formatting and only the top-level version', () => {
  const src = '{\n  "name": "x",\n  "version": "1.0.0",\n  "scripts": { "version": "echo v" },\n  "keywords": ["a", "b"]\n}\n';
  const out = bumpJson(src, '1.2.3');
  assert.equal(out, src.replace('"version": "1.0.0"', '"version": "1.2.3"'));
  assert.equal(JSON.parse(out).scripts.version, 'echo v');
});

test('bumpJson inserts version after name when asked', () => {
  const src = '{\n  "name": "cortexmd",\n  "private": true\n}\n';
  const out = bumpJson(src, '1.2.3', { addIfMissing: true });
  assert.equal(JSON.parse(out).version, '1.2.3');
  assert.ok(out.startsWith('{\n  "name": "cortexmd",\n  "version": "1.2.3",\n  "private": true'));
  assert.throws(() => bumpJson(src, '1.2.3'), /no top-level "version"/);
});

test('bumpAll updates every target in a fixture repo and skips absent lockfile', () => {
  const root = fixtureRepo();
  try {
    const report = bumpAll(root, '1.19.0');
    const byPath = Object.fromEntries(report.map((r) => [r.path, r.status]));
    assert.equal(byPath['crates/cli/Cargo.toml'], 'updated');
    assert.equal(byPath['Cargo.lock'], 'updated');
    assert.equal(byPath['crates/cli/Cargo.lock'], 'skipped (absent)');
    assert.equal(byPath['packages/server/package.json'], 'updated');
    assert.equal(byPath['package.json'], 'updated');
    assert.equal(byPath['plugin/cortexmd/.claude-plugin/plugin.json'], 'updated');
    assert.equal(report.length, TARGETS.length);

    assert.match(readFileSync(join(root, 'crates', 'cli', 'Cargo.toml'), 'utf8'), /^version = "1\.19\.0"$/m);
    assert.ok(readFileSync(join(root, 'Cargo.lock'), 'utf8').includes('name = "cortexmd-cli"\nversion = "1.19.0"'));
    assert.equal(JSON.parse(readFileSync(join(root, 'packages', 'server', 'package.json'), 'utf8')).version, '1.19.0');
    assert.equal(JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version, '1.19.0');
    const plugin = readFileSync(join(root, 'plugin', 'cortexmd', '.claude-plugin', 'plugin.json'), 'utf8');
    assert.equal(JSON.parse(plugin).version, '1.19.0');
    assert.ok(plugin.includes('"keywords": ["mcp", "memory"]'), 'plugin.json formatting preserved');

    // Idempotent: a second run reports everything unchanged.
    const again = bumpAll(root, '1.19.0');
    assert.ok(again.filter((r) => r.status === 'updated').length === 0);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('bumpAll rejects non-semver input and dry-run writes nothing', () => {
  const root = fixtureRepo();
  try {
    assert.throws(() => bumpAll(root, 'latest'), /not a semver/);
    const before = readFileSync(join(root, 'Cargo.lock'), 'utf8');
    const report = bumpAll(root, '3.0.0', { dryRun: true });
    assert.ok(report.some((r) => r.status === 'would update'));
    assert.equal(readFileSync(join(root, 'Cargo.lock'), 'utf8'), before);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('CLI entry point: node scripts/bump-version.mjs <version> --root <dir> (accepts v-prefix)', () => {
  const root = fixtureRepo();
  try {
    const out = execFileSync(process.execPath, [SCRIPT, 'v1.20.1', '--root', root], { encoding: 'utf8' });
    assert.match(out, /bump-version: 1\.20\.1/);
    assert.equal(JSON.parse(readFileSync(join(root, 'plugin', 'cortexmd', '.claude-plugin', 'plugin.json'), 'utf8')).version, '1.20.1');
    assert.match(readFileSync(join(root, 'crates', 'cli', 'Cargo.toml'), 'utf8'), /^version = "1\.20\.1"$/m);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
